
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ResourceBundle;
import javax.swing.text.BadLocationException;
import javax.swing.text.rtf.RTFEditorKit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pmateo
 */
public class Ayuda extends javax.swing.JFrame {
    private ResourceBundle bundle;
    /**
     * Creates new form Ayuda
     */
    public Ayuda(ResourceBundle bndl, int caretPos) {
        
        bundle = bndl;
        initComponents();
        
        RTFEditorKit rtf = new RTFEditorKit();
        EditorPaneAyuda.setEditorKit(rtf);
        EditorPaneAyuda.setBackground(Color.white);
        try {
            FileInputStream fi = new FileInputStream("Tool User Guide.rtf");
            rtf.read(fi, EditorPaneAyuda.getDocument(), 0);
        } catch (FileNotFoundException e) {
            
        } catch (IOException e) {

        } catch (BadLocationException e) {
        }
        EditorPaneAyuda.setCaretPosition(caretPos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EditorPaneAyuda = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        ButtonCerrarAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("ayuda.pantalla.title")
        );
        setBounds(new java.awt.Rectangle(0, 0, 800, 700));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 800));
        jPanel1.setLayout(new java.awt.BorderLayout());

        EditorPaneAyuda.setEditable(false);
        EditorPaneAyuda.setContentType("text/rtf");
        jScrollPane1.setViewportView(EditorPaneAyuda);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        ButtonCerrarAyuda.setText(bundle.getString("general.button.cerrarayuda"));
        getContentPane().add(ButtonCerrarAyuda, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCerrarAyuda;
    private javax.swing.JEditorPane EditorPaneAyuda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
