
import com.ibm.icu.util.Calendar;
import java.io.File;
import java.io.StringWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ResourceBundle;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author pmateo
 */
public class InputsPreprocesoValidacion extends javax.swing.JDialog {

    private String dataDirectory;
    private String lastDirectoryVisited;
    private String nombreFicheroPrevio;
  //  private String newOwnPositivesFile;
    private final JTextArea salidaTexto;
    private final ScriptEngineManager factory;
    private final ScriptEngine engine;
    private final StringWriter outputWriter;
    private final PantallaPrincipalA ppa;
    private final String ficheros[];
    private final JButton resTextoButon;
    private final JButton resGraphicButon;
    private final JButton resTextoButon2;
    private final JButton resGraphicButon2;
    private Date tMin;
    private Date tMax;
    private boolean ficheroDatosDisponible;
    private boolean usarDirectorioTemporales = true;
    private ResourceBundle bundle;

    /**
     * Creates new form InputsPreproceso
     *
     * @param parent
     * @param modal
     * @param DD
     * @param LD
     * @param nfa
     * @param jta
     * @param fichs
     */
    public InputsPreprocesoValidacion(java.awt.Frame parent, boolean modal, String DD, String LD, String nfa, JTextArea jta, 
            String fichs[], JButton jBResText, JButton jBResGrf, JButton jBResText2, JButton jBResGrf2,ResourceBundle bndl) {
        super(parent, modal);
        ppa = (PantallaPrincipalA) parent;
        File f; 
        bundle=bndl;
        initComponents();
        dataDirectory = DD;
        lastDirectoryVisited = LD;
        nombreFicheroPrevio = nfa;
        ficheros = fichs;
        resTextoButon = jBResText;
        resGraphicButon = jBResGrf;
        resTextoButon2 = jBResText2;
        resGraphicButon2 = jBResGrf2;
       

        if (nfa != null) {
            f = new File(nombreFicheroPrevio);
            if (f.exists()) {
                nombreFicheroJTF.setText(nombreFicheroPrevio);
            } else {
                nombreFicheroJTF.setText("");
            }
        } else {
            nombreFicheroJTF.setText("");
        }
        salidaTexto = jta;
        factory = new ScriptEngineManager();
        // create a Renjin engine
        engine = factory.getEngineByName("Renjin");
        outputWriter = new StringWriter();
        engine.getContext().setWriter(outputWriter);
        ficheroDatosDisponible = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreFicheroJTF = new javax.swing.JTextField();
        cargarFicheroDatos = new javax.swing.JButton();
        jDateChooser_t_I = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        seleccionarFicheroDatos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser_t_F = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechaIni = new javax.swing.JTextField();
        fechaFin = new javax.swing.JTextField();
        procesar2 = new javax.swing.JButton();
        cancelar2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser_t_0 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser_t_1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        semillaJTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numRepJTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("validacion.pantalla.title"));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(684, 331));

        jLabel1.setText(bundle.getString("validacion.pantalla.label.ficherodatos")
        );

        nombreFicheroJTF.setToolTipText("Fichero de datos para estimar parámetros del modelo");
        nombreFicheroJTF.setMaximumSize(new java.awt.Dimension(250, 23));
        nombreFicheroJTF.setMinimumSize(new java.awt.Dimension(150, 23));
        nombreFicheroJTF.setPreferredSize(new java.awt.Dimension(150, 23));

        cargarFicheroDatos.setText(bundle.getString("validacion.pantalla.button.cargar"));
        cargarFicheroDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFicheroDatosActionPerformed(evt);
            }
        });

        jDateChooser_t_I.setDateFormatString("yyyy-MM-dd");
        jDateChooser_t_I.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser_t_IPropertyChange(evt);
            }
        });

        jLabel2.setText(bundle.getString("validacion.pantalla.label.periodoestimacion"));

        seleccionarFicheroDatos.setText(bundle.getString("validacion.pantalla.button.seleccionar"));
        seleccionarFicheroDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarFicheroDatosActionPerformed(evt);
            }
        });

        jLabel3.setText(bundle.getString("validacion.pantalla.label.to"));
        jLabel3.setMaximumSize(new java.awt.Dimension(63, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(63, 15));
        jLabel3.setName(""); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(63, 15));

        jDateChooser_t_F.setDateFormatString("yyyy-MM-dd");
        jDateChooser_t_F.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser_t_FPropertyChange(evt);
            }
        });

        jLabel4.setText(bundle.getString("validacion.pantalla.label.periodofichero"));
        jLabel4.setMaximumSize(new java.awt.Dimension(250, 15));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 15));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 15));

        jLabel5.setText(bundle.getString("validacion.pantalla.label.to"));
        jLabel5.setMaximumSize(new java.awt.Dimension(63, 15));
        jLabel5.setMinimumSize(new java.awt.Dimension(63, 15));
        jLabel5.setPreferredSize(new java.awt.Dimension(63, 15));

        fechaIni.setEditable(false);
        fechaIni.setMaximumSize(new java.awt.Dimension(100, 23));
        fechaIni.setPreferredSize(new java.awt.Dimension(75, 23));

        fechaFin.setEditable(false);
        fechaFin.setMaximumSize(new java.awt.Dimension(125, 23));
        fechaFin.setPreferredSize(new java.awt.Dimension(75, 23));

        procesar2.setText(bundle.getString("validacion.pantalla.button.procesar"));
        procesar2.setEnabled(false);
        procesar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesar2ActionPerformed(evt);
            }
        });

        cancelar2.setText(bundle.getString("validacion.pantalla.button.cancelar"));
        cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar2ActionPerformed(evt);
            }
        });

        jLabel6.setText(bundle.getString("validacion.pantalla.label.periodoprediccion"));
        jLabel6.setAlignmentY(0.0F);

        jDateChooser_t_0.setDateFormatString("yyyy-MM-dd");
        jDateChooser_t_0.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser_t_0PropertyChange(evt);
            }
        });

        jLabel7.setText(bundle.getString("validacion.pantalla.label.to"));
        jLabel7.setMaximumSize(new java.awt.Dimension(63, 15));
        jLabel7.setMinimumSize(new java.awt.Dimension(63, 15));
        jLabel7.setName(""); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(63, 15));

        jDateChooser_t_1.setDateFormatString("yyyy-MM-dd");
        jDateChooser_t_1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser_t_1PropertyChange(evt);
            }
        });

        jLabel8.setText(bundle.getString("validacion.pantalla.label.semilla"));

        semillaJTF.setText("29088334");

        jLabel9.setText(bundle.getString("validacion.pantalla.label.numeroreplicas"));

        numRepJTF.setText("2000");

        jButton1.setText(bundle.getString("general.button.ayuda"));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(procesar2)
                            .addGap(32, 32, 32)
                            .addComponent(cancelar2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(28, 28, 28)
                                    .addComponent(semillaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(numRepJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombreFicheroJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(seleccionarFicheroDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(185, 185, 185)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cargarFicheroDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDateChooser_t_0, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDateChooser_t_I, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser_t_F, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser_t_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreFicheroJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargarFicheroDatos)
                    .addComponent(seleccionarFicheroDatos))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser_t_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_t_I, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_t_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser_t_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(numRepJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(semillaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(procesar2)
                    .addComponent(cancelar2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarFicheroDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFicheroDatosActionPerformed
           leeTesteaHistoricalRecordsValidacion lthrv = new leeTesteaHistoricalRecordsValidacion(bundle, engine,nombreFicheroPrevio,salidaTexto,fechaIni,fechaFin,nombreFicheroJTF,
                                            jDateChooser_t_0,jDateChooser_t_1,jDateChooser_t_F,jDateChooser_t_I,dataDirectory,procesar2,ficheroDatosDisponible,outputWriter);
            lthrv.execute();
      
    }//GEN-LAST:event_cargarFicheroDatosActionPerformed

    private void seleccionarFicheroDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarFicheroDatosActionPerformed
        // TODO add your handling code here:
        String outPut;
        File ff;
        //Pedimos el fichero con la información raw
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle(bundle.getString("mensaje.seleccionaficherodatos"));
        if (lastDirectoryVisited != null) {
            ff = new File(lastDirectoryVisited);
            if (ff.isDirectory()) {
                jfc.setCurrentDirectory(ff);
            }
        }
        FileFilter filter = new FileNameExtensionFilter(bundle.getString("mensaje.nombreextension"), "csv", "txt");
        jfc.setFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        int resultado = jfc.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            if (jfc.getSelectedFile().exists()) {
                lastDirectoryVisited = jfc.getSelectedFile().getParent();
                nombreFicheroPrevio = jfc.getSelectedFile().getAbsolutePath();
                nombreFicheroJTF.setText(nombreFicheroPrevio);
                nombreFicheroJTF.setToolTipText(nombreFicheroPrevio);
               // salidaTexto.append("\n\nFichero seleccionado para procesar: " + nombreFicheroPrevio);
                procesar2.setEnabled(false);
                this.ficheroDatosDisponible = false;
            } else {
                JOptionPane.showMessageDialog(this, String.format(bundle.getString("error.ficheronoexiste"),jfc.getSelectedFile().getAbsolutePath()));

//                JOptionPane.showMessageDialog(this, "El fichero de datos raw debe existir");
            }
        }
    }//GEN-LAST:event_seleccionarFicheroDatosActionPerformed

    private void procesar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesar2ActionPerformed
        // TODO add your handling code here:
        String outPut;
        int numReplicas;
        int semilla;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        if (jDateChooser_t_I.getDate() == null || jDateChooser_t_F.getDate() == null
                || jDateChooser_t_0.getDate() == null
                || jDateChooser_t_1.getDate() == null) {
            JOptionPane.showMessageDialog(this, bundle.getString("error.fechasnecesarias"));
            return;
        }
        
        //Lo primero generamos los ficheros, y posteriormente simulamos dos veces
        

            String freqSer=null;
            int numero=0;
            try{
                freqSer =JOptionPane.showInputDialog(this,bundle.getString("mensaje.parametrofrequencyseries"), 7);
                numero=Integer.parseInt(freqSer);
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(this, String.format(bundle.getString("error.paramfreqseries"),freqSer));
                return;
            }
            
            salidaTexto.append(String.format(bundle.getString("mensaje.periodoestimacion"),sdf.format(jDateChooser_t_I.getDate()),
                 sdf.format(jDateChooser_t_F.getDate()) ));
            salidaTexto.append(String.format(bundle.getString("mensaje.periodoprediccion"),sdf.format(jDateChooser_t_0.getDate()),
                 sdf.format(jDateChooser_t_1.getDate()) ));
            
            estimaParametrosYSimulaValidacion ePPS= new estimaParametrosYSimulaValidacion(bundle,engine,salidaTexto,jDateChooser_t_0,jDateChooser_t_1,jDateChooser_t_F,
                 jDateChooser_t_I,dataDirectory,procesar2,outputWriter,numero,ppa,nombreFicheroPrevio,lastDirectoryVisited,ficheros,semillaJTF,numRepJTF,
                 resTextoButon,resGraphicButon,resTextoButon2,resGraphicButon2);
        ePPS.execute();
        this.dispose();

    }//GEN-LAST:event_procesar2ActionPerformed

    private void cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar2ActionPerformed
        // TODO add your handling code here:
      if(JOptionPane.showConfirmDialog(this, bundle.getString("mensaje.salirprocesadoficheros"))==JOptionPane.OK_OPTION){
            ppa.setDataDirectory(dataDirectory);
            ppa.setLastDirectoryVisited(lastDirectoryVisited);
            ppa.setLastFileUsed(nombreFicheroPrevio);
//            ppa.setFrom(LocalDate.of(1900+jDateChooser_t_0.getDate().getYear(), jDateChooser_t_0.getDate().getMonth()+1, jDateChooser_t_0.getDate().getDate()));
            //           ppa.setUntil(LocalDate.of(1900+jDateChooser_t_1.getDate().getYear(), jDateChooser_t_1.getDate().getMonth()+1, jDateChooser_t_1.getDate().getDate()));
            this.dispose();
        }
    }//GEN-LAST:event_cancelar2ActionPerformed

    private void jDateChooser_t_IPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser_t_IPropertyChange
        // TODO add your handling code here:

        if (jDateChooser_t_I.getDate() != null) {
            Calendar cc = Calendar.getInstance();
            cc.setTime(jDateChooser_t_I.getDate());
            cc.add(Calendar.DATE, 1);
            jDateChooser_t_F.setMinSelectableDate(cc.getTime());

        }
    }//GEN-LAST:event_jDateChooser_t_IPropertyChange

    private void jDateChooser_t_FPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser_t_FPropertyChange
        // TODO add your handling code here:
        if (jDateChooser_t_F.getDate() != null) {
            Calendar cc = Calendar.getInstance();
            cc.setTime(jDateChooser_t_F.getDate());
            cc.add(Calendar.DATE, -1);
            jDateChooser_t_I.setMaxSelectableDate(cc.getTime());
            cc.add(Calendar.DATE, 2);
            jDateChooser_t_0.setMinSelectableDate(cc.getTime());
        }
    }//GEN-LAST:event_jDateChooser_t_FPropertyChange

    private void jDateChooser_t_0PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser_t_0PropertyChange
        // TODO add your handling code here:
        if (jDateChooser_t_0.getDate() != null) {
            Calendar cc = Calendar.getInstance();
            cc.setTime(jDateChooser_t_0.getDate());
            cc.add(Calendar.DATE, 1);
            jDateChooser_t_1.setMinSelectableDate(cc.getTime());
        }
    }//GEN-LAST:event_jDateChooser_t_0PropertyChange

    private void jDateChooser_t_1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser_t_1PropertyChange
        // TODO add your handling code here:
        if (jDateChooser_t_1.getDate() != null) {
            Calendar cc = Calendar.getInstance();

            if (jDateChooser_t_1.getDate().before(jDateChooser_t_F.getMaxSelectableDate())) {
                cc.setTime(jDateChooser_t_1.getDate());
                cc.add(Calendar.DATE, -1);
                jDateChooser_t_0.setMaxSelectableDate(cc.getTime());
            } else {
                jDateChooser_t_0.setMaxSelectableDate(jDateChooser_t_F.getMaxSelectableDate());
            }
        }
    }//GEN-LAST:event_jDateChooser_t_1PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Ayuda a = new Ayuda(bundle,Integer.parseInt(bundle.getString("ayuda.caretPosition.forecasting")));
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar2;
    private javax.swing.JButton cargarFicheroDatos;
    private javax.swing.JTextField fechaFin;
    private javax.swing.JTextField fechaIni;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser_t_0;
    private com.toedter.calendar.JDateChooser jDateChooser_t_1;
    private com.toedter.calendar.JDateChooser jDateChooser_t_F;
    private com.toedter.calendar.JDateChooser jDateChooser_t_I;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreFicheroJTF;
    private javax.swing.JTextField numRepJTF;
    private javax.swing.JButton procesar2;
    private javax.swing.JButton seleccionarFicheroDatos;
    private javax.swing.JTextField semillaJTF;
    // End of variables declaration//GEN-END:variables
}
