
import java.util.ResourceBundle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pmateo
 */
public class showProgress extends javax.swing.JFrame {

    
    private ResourceBundle bundle;
    /**
     * @return the barraProgreso
     */
    public javax.swing.JProgressBar getBarraProgreso() {        
        return barraProgreso;
    }


    /**
     * Creates new form showProgress
     */
    public showProgress(ResourceBundle bndl,String wTitle) {
        bundle=bndl;
        initComponents();       
        this.setTitle(wTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        barraProgreso = new javax.swing.JProgressBar();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 60));
        setMinimumSize(new java.awt.Dimension(450, 20));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(450, 70));
        setResizable(false);

        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 50));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(filler1);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("showprogress.esperar"));
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(450, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(450, 20));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(450, 20));
        jPanel1.add(jLabel1);
        jPanel1.add(filler3);

        barraProgreso.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        barraProgreso.setForeground(new java.awt.Color(204, 204, 255));
        barraProgreso.setAlignmentX(0.0F);
        barraProgreso.setAlignmentY(0.0F);
        barraProgreso.setBorder(new javax.swing.border.MatteBorder(null));
        barraProgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraProgreso.setMaximumSize(new java.awt.Dimension(450, 10));
        barraProgreso.setMinimumSize(new java.awt.Dimension(450, 10));
        barraProgreso.setPreferredSize(new java.awt.Dimension(450, 10));
        jPanel1.add(barraProgreso);
        jPanel1.add(filler2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
